### ISSUE TITLE
Implement project structure folders and files

### ISSUE THREAD

**Issue by goatsweater** [canmet-energy/btap_ml#1]
Implement common project scaffolding elements to support best practices.

Major components:
* gitignore for Python + DS
* code linting
* scratch data isolation
* documentation
* testing

**Comment by goatsweater** [comment]
Pushed a `.gitignore` and basic `requirements.txt` file to get started.

**Comment by maybuksho** [comment]
@goatsweater are we implementing testing for this project? Not sure if this is part of the deliverables or we are looking at best practice here .

The folder structure is already defined except for testing. Please let me know what the plan is.

**Comment by goatsweater** [comment]
I don't think we have any required tests as deliverables. Where it makes sense we should implement testing to ensure changes don't break things, but no need to have 100% coverage at this stage.
