### ISSUE TITLE
Automate weather data processing

### ISSUE THREAD

**Issue by goatsweater** [canmet-energy/btap_ml#13]
Weather data (.epw file) was originally processed by hand to develop the input to the ML model. The work required to process this file should be automated (and documented) as part of an early pipeline step.

Weather location of interest is identified through the YAML config file parameter `:epw_file`. Downloads from https://energyplus.net/weather are not exactly what is being used in the config file. Need to document proper source.

**Comment by goatsweater** [comment]
Documentation of the EPW file format can be found at https://energyplus.net/assets/nrel_custom/pdfs/pdfs_v9.6.0/AuxiliaryPrograms.pdf, around page 25.

**Comment by goatsweater** [comment]
@ckirney Do you know how EnergyPlus takes the `:epw_file` value and knows where to get the file from?

Looking at the current YAML config we have:

```
:epw_file: [
      'CAN_QC_Montreal-Trudeau.Intl.AP.716270_CWEC2016.epw',
    #'CAN_NS_Halifax.Dockyard.713280_CWEC2016.epw',
    #'CAN_AB_Edmonton.Intl.AP.711230_CWEC2016.epw',
    #'CAN_BC_Vancouver.Intl.AP.718920_CWEC2016.epw',
    #'CAN_AB_Calgary.Intl.AP.718770_CWEC2016.epw',
    #'CAN_ON_Toronto.Pearson.Intl.AP.716240_CWEC2016.epw',
    #'CAN_YT_Whitehorse.Intl.AP.719640_CWEC2016.epw'
  ]
```

When I go to https://energyplus.net/weather it gives me a file name `CAN_PQ_Montreal.Intl.AP.716270_CWEC.epw` rather than `CAN_QC_Montreal-Trudeau.Intl.AP.716270_CWEC2016.epw`. Perhaps BTAP is using custom weather files from a different source?

**Comment by ckirney** [comment]
When we do a simulation we provide the epw file to E+ (well, we provide it to OpenStudio which ultimately provides it to E+).  BTAP automates the whole process and we currently store the weather files we use in a folder in the openstudio-standards repository here:

https://github.com/NREL/openstudio-standards/tree/nrcan/data/weather

If you look in the above repo you can select any of the weather files there and add the name to the yml file.  If you want to use something different, you can get your own epw file, add it to the repo in the above folder (ideally in a different branch), and add it to the yml file (along with the name of the branch it is on).  You will need to store .stat and .ddy files in the same location as the .epw file too, but you usually can get those from the same place as the epw file.

You can get alternate weather files from many sources or, if you really want, make your own.  The E+ site is one source, but we get a lot of our files from here:
https://climate.onebuilding.org/WMO_Region_4_North_and_Central_America/CAN_Canada/index.html

Environment and Climate Change Canada also provides a number of different climate data sets for energy modelling which you can get here:
https://climate.weather.gc.ca/prods_servs/engineering_e.html

Unfortunately, they generally provide it in a format that must be converted to the epw format that E+ uses.  It can be done but it is an extra step that sometimes has problems.

**Comment by goatsweater** [comment]
A new script has been introduced to automatically process the weather data. The script will use the file name(s) specified in the config `:epw_file` parameter, download them from the `NREL/openstudio-standards` repo, and prepare them for use. It will then save them to S3 to be used in later steps.

Given the work that is being performed on the weather data, this can replace the existing `read_weather()` function in `preprocessing.py`. Changes have not yet been implemented to avoid the work being done in `read_weather()`, so loading the output of this script would cause an error at the moment.
