### ISSUE TITLE
Kubeflow Pipleline

### ISSUE THREAD

**Issue by maybuksho** [canmet-energy/btap_ml#5]
Create the kubeflow pipeline components, 
- docker files
- yaml files
- Check to ensure the pipleline works as expected

**Comment by goatsweater** [comment]
AAW restricts where it'll pull docker images from. The CI pipeline to auto-run the pipeline needs to create the images within the AAW environment and pull the code from this repo to run it.

**Comment by maybuksho** [comment]
Work is ongoing in developing the pipeline. The image is already pushed to the repository, the pipeline is also uploaded to kubeflow. However, attempt to pull the image while running the pipline is failing because of authentication issues most likely. We will need to look more into this when AAW is available again.

**Comment by goatsweater** [comment]
Kubeflow was timing out when trying to connect to minio. Problem was discovered with sidecar injection and fixed by AAW tech team.

Pipeline is now running, but exiting on an encoding error in `preprocessing.py` to be looked at.

**Comment by goatsweater** [comment]
Attempts to verify the problem yesterday showed that there is a race condition where we are attempting to load credentials from the vault file, but those credentials haven't been added to the pod yet. Tracing reveals that it sometimes takes up to 5 seconds for the credentials to appear.

The settings loader that reads from the credential store should have a retry step for loading credentials, warning when attempts to read fail and eventually giving an error after some timeout is reached.

**Comment by goatsweater** [comment]
The credential loaded now checks for the file and does a wait/retry cycle if not found. Merge into the container submitted in https://github.com/StatCan/aaw-contrib-containers/pull/69

**Comment by goatsweater** [comment]
The current CPU/RAM restrictions on the pipeline end up reducing the overall pool of available nodes that are able to process each step. It's likely the contention will only get higher as more projects are onboarded to AAW. We should try to strategize on what can be done to reduce overall requirements in future iterations of the project.

**Comment by maybuksho** [comment]
Pipleline completed successfully.
