### ISSUE TITLE
Centralize minio access setup

### ISSUE THREAD

**Issue by goatsweater** [canmet-energy/btap_ml#9]
The `access_minio`  function is repeated across multiple files and can be centralized and reused.

There are a few considerations with centralizing this function, since it is responsible for a few items:

* Loading settings, including Vault keys
* Establishing a connection to S3 (minio)
* Reading a dataset from a bucket
* Writing a dataset to a bucket
* Returning the data

These concerns can be separated out somewhat to make portability easier, but doing this will necessitate changing a few different spots in the code.

**Comment by maybuksho** [comment]
Resolved, the config.py file is created.
